[project]
name = "github-copilot-workshop"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "python-pptx>=1.0.2",
    "pillow>=10.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.3.4",
    "pytest-cov>=6.0.0",
    "ruff>=0.8.0",
]
