blank_issues_enabled: false
contact_links:
  - name: Ask a question (Discussions)
    url: https://github.com/huangyingting/github-copilot-workshop/discussions/new?category=q-a
    about: Q&A and general help